// <auto-generated />
using System;
using FraudGuard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FraudGuard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722180102_UpdateDemoEmailDomain")]
    partial class UpdateDemoEmailDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FraudGuard.Api.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SwiftCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SwiftCode")
                        .IsUnique();

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Kosovo",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Raiffeisen Bank Kosovo",
                            SwiftCode = "RBKODEMO"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Kosovo",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ProCredit Bank Kosovo",
                            SwiftCode = "PCBKKDEMO"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Kosovo",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "NLB Banka",
                            SwiftCode = "NLBADEMO"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Kosovo",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "TEB Bank",
                            SwiftCode = "TEBKDEMO"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Kosovo",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "BKT Kosovo",
                            SwiftCode = "BKTKDEMO"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Kosovo",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Banka Ekonomike",
                            SwiftCode = "BEKODEMO"
                        });
                });

            modelBuilder.Entity("FraudGuard.Api.Models.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValue("Simulated Account Holder");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Simulated Account");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("BankId");

                    b.HasIndex("IBAN")
                        .IsUnique();

                    b.HasIndex("UserId", "BankId", "AccountType")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL AND [IsActive] = 1");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            AccountHolderName = "Demo Merchant Settlement",
                            AccountName = "Demo Merchant Settlement",
                            AccountNumber = "FGD-MERCH-4102",
                            AccountType = "Merchant Settlement",
                            BankId = 5,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            CurrentBalance = 82000.00m,
                            IBAN = "XK051212000000014102",
                            IsActive = true,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 6,
                            AccountHolderName = "Demo Merchant Settlement",
                            AccountName = "Demo Merchant Settlement",
                            AccountNumber = "FGD-MERCH-9820",
                            AccountType = "Merchant Settlement",
                            BankId = 6,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            CurrentBalance = 64000.00m,
                            IBAN = "XK051212000000019820",
                            IsActive = true,
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("FraudGuard.Api.Models.BankAccountVerificationAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountLookupHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AccountLookupHash", "AttemptedAt");

                    b.ToTable("BankAccountVerificationAttempts");
                });

            modelBuilder.Entity("FraudGuard.Api.Models.Beneficiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DestinationBankAccountId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("bit");

                    b.Property<string>("MaskedAccountReference")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("DestinationBankAccountId");

                    b.HasIndex("UserId", "FullName", "MaskedAccountReference");

                    b.ToTable("Beneficiaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankId = 3,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Demo Family Transfer",
                            IsTrusted = true,
                            MaskedAccountReference = "•••• 1188",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BankId = 6,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Demo Supplier Account",
                            IsTrusted = false,
                            MaskedAccountReference = "•••• 7742",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FraudGuard.Api.Models.DemoBankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DevelopmentUserId")
                        .HasColumnType("int");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLinked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LinkedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LinkedUserId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationCodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("BankId");

                    b.HasIndex("DevelopmentUserId");

                    b.HasIndex("Iban")
                        .IsUnique();

                    b.HasIndex("LinkedUserId");

                    b.HasIndex("DevelopmentUserId", "BankId")
                        .IsUnique()
                        .HasFilter("[DevelopmentUserId] IS NOT NULL");

                    b.ToTable("DemoBankAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountHolderName = "Fiona Ajeti",
                            AccountNumber = "1000123456",
                            AccountType = "Current",
                            BankId = 1,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            CurrentBalance = 5000m,
                            Iban = "XK051234567890123456",
                            IsActive = true,
                            IsLinked = false,
                            RowVersion = new byte[0],
                            VerificationCodeHash = "F724A30965E1FBA1EA7CA65F0B0D600572D0D61081053F7C0483DBC66F569C32"
                        },
                        new
                        {
                            Id = 2,
                            AccountHolderName = "Arben Krasniqi",
                            AccountNumber = "2000123456",
                            AccountType = "Savings",
                            BankId = 2,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            CurrentBalance = 10000m,
                            Iban = "XK052234567890123456",
                            IsActive = true,
                            IsLinked = false,
                            RowVersion = new byte[0],
                            VerificationCodeHash = "518810C012FE56C8C0A4BEE3E081CE803696900FB1FA4935AD975E82D0729359"
                        },
                        new
                        {
                            Id = 3,
                            AccountHolderName = "Lira Gashi",
                            AccountNumber = "3000123456",
                            AccountType = "Current",
                            BankId = 3,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            CurrentBalance = 7200m,
                            Iban = "XK053234567890123456",
                            IsActive = true,
                            IsLinked = false,
                            RowVersion = new byte[0],
                            VerificationCodeHash = "B79E8098800EAD554EB209EAC3A33A424CDF3D74C97C856E12F1D14788FC070E"
                        },
                        new
                        {
                            Id = 4,
                            AccountHolderName = "Dardan Berisha",
                            AccountNumber = "4000123456",
                            AccountType = "Savings",
                            BankId = 4,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            CurrentBalance = 12500m,
                            Iban = "XK054234567890123456",
                            IsActive = true,
                            IsLinked = false,
                            RowVersion = new byte[0],
                            VerificationCodeHash = "35EE79ED144A5EA1651070092B24490BD6B1E860770014AB785EDE76BEE3FD6F"
                        },
                        new
                        {
                            Id = 5,
                            AccountHolderName = "Elira Morina",
                            AccountNumber = "5000123456",
                            AccountType = "Current",
                            BankId = 5,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            CurrentBalance = 6400m,
                            Iban = "XK055234567890123456",
                            IsActive = true,
                            IsLinked = false,
                            RowVersion = new byte[0],
                            VerificationCodeHash = "7C12876906BF253B6FE18C413F6D7EC3B0005280ADB98C549B92BB6AFFFF2CAB"
                        },
                        new
                        {
                            Id = 6,
                            AccountHolderName = "Besnik Hoxha",
                            AccountNumber = "6000123456",
                            AccountType = "Savings",
                            BankId = 6,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            CurrentBalance = 15000m,
                            Iban = "XK056234567890123456",
                            IsActive = true,
                            IsLinked = false,
                            RowVersion = new byte[0],
                            VerificationCodeHash = "68012CE7110B4F58E50F7605C9AE08C04759B8EF9CE45A30DAF4C7B438B673DE"
                        },
                        new
                        {
                            Id = 7,
                            AccountHolderName = "Fiona Ajeti",
                            AccountNumber = "3100102157",
                            AccountType = "Current",
                            BankId = 3,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            CurrentBalance = 8300m,
                            Iban = "XK053100102157000001",
                            IsActive = true,
                            IsLinked = false,
                            RowVersion = new byte[0],
                            VerificationCodeHash = "F724A30965E1FBA1EA7CA65F0B0D600572D0D61081053F7C0483DBC66F569C32"
                        });
                });

            modelBuilder.Entity("FraudGuard.Api.Models.FraudAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PredictionId")
                        .HasColumnType("int");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredictionId");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.HasIndex("TransactionId", "Status");

                    b.ToTable("FraudAlerts");
                });

            modelBuilder.Entity("FraudGuard.Api.Models.FraudCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalystComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("AssignedAnalystId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalDecision")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("FraudAlertId")
                        .HasColumnType("int");

                    b.Property<string>("ModelDecision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ModelRiskScore")
                        .HasColumnType("int");

                    b.Property<int?>("PredictionId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAnalystId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FraudAlertId");

                    b.HasIndex("PredictionId");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("FraudCases");
                });

            modelBuilder.Entity("FraudGuard.Api.Models.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("SettlementBankAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("SettlementBankAccountId");

                    b.ToTable("Merchants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Retail",
                            Country = "Kosovo",
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Demo Market Prishtina",
                            RiskLevel = "Low",
                            SettlementBankAccountId = 5
                        },
                        new
                        {
                            Id = 2,
                            Category = "Travel",
                            Country = "Kosovo",
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Demo Travel Agency",
                            RiskLevel = "Medium",
                            SettlementBankAccountId = 6
                        },
                        new
                        {
                            Id = 3,
                            Category = "E-Commerce",
                            Country = "Kosovo",
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Demo Electronics Store",
                            RiskLevel = "Low",
                            SettlementBankAccountId = 5
                        },
                        new
                        {
                            Id = 4,
                            Category = "Crypto",
                            Country = "Kosovo",
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Demo Crypto Exchange",
                            RiskLevel = "High",
                            SettlementBankAccountId = 6
                        });
                });

            modelBuilder.Entity("FraudGuard.Api.Models.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFraud")
                        .HasColumnType("bit");

                    b.Property<decimal>("NewBalanceDestination")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewBalanceOrigin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldBalanceDestination")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldBalanceOrigin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("FraudGuard.Api.Models.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Method")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Path")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Level");

                    b.HasIndex("Source");

                    b.HasIndex("UserId");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("FraudGuard.Api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BeneficiaryId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("MerchantId")
                        .HasColumnType("int");

                    b.Property<decimal?>("NewBalanceDestination")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NewBalanceOrigin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OldBalanceDestination")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OldBalanceOrigin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("RiskScore")
                        .HasColumnType("int");

                    b.Property<int?>("SourceBankAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MerchantId");

                    b.HasIndex("SourceBankAccountId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 129.99m,
                            Category = "Retail",
                            Country = "United States",
                            CreatedAt = new DateTime(2026, 1, 2, 10, 15, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Office equipment purchase",
                            Merchant = "Amazon",
                            ProcessingStatus = "Completed",
                            RiskScore = 18,
                            Status = "safe",
                            TransactionType = "PAYMENT",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 4250m,
                            Category = "Money Transfer",
                            Country = "Nigeria",
                            CreatedAt = new DateTime(2026, 1, 3, 2, 35, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "High-value transfer to new destination",
                            Merchant = "QuickCash Transfer",
                            ProcessingStatus = "Rejected",
                            RiskScore = 78,
                            Status = "fraud",
                            TransactionType = "TRANSFER",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 860m,
                            Category = "Travel",
                            Country = "Germany",
                            CreatedAt = new DateTime(2026, 1, 4, 18, 20, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Travel booking flagged for review",
                            Merchant = "Booking",
                            ProcessingStatus = "PendingReview",
                            RiskScore = 44,
                            Status = "review",
                            TransactionType = "PAYMENT",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("FraudGuard.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@fraudguard.com",
                            FullName = "FraudGuard User",
                            IsActive = true,
                            PasswordHash = "$2a$11$753ccYgfz2QJHlSCTMG2a.Swts8DhWf9WAQJQtEz3HN3AUsIHMIXO",
                            Role = "User"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@fraudguard.com",
                            FullName = "FraudGuard Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$hMS2w0HZwNwlHWet4HN1Ce.tzShAq1G7pJ30aYBQawVUxjn3a.IJC",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("FraudGuard.Api.Models.BankAccount", b =>
                {
                    b.HasOne("FraudGuard.Api.Models.Bank", "Bank")
                        .WithMany("BankAccounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FraudGuard.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Bank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FraudGuard.Api.Models.Beneficiary", b =>
                {
                    b.HasOne("FraudGuard.Api.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FraudGuard.Api.Models.BankAccount", "DestinationBankAccount")
                        .WithMany()
                        .HasForeignKey("DestinationBankAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FraudGuard.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("DestinationBankAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FraudGuard.Api.Models.DemoBankAccount", b =>
                {
                    b.HasOne("FraudGuard.Api.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FraudGuard.Api.Models.User", "DevelopmentUser")
                        .WithMany()
                        .HasForeignKey("DevelopmentUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FraudGuard.Api.Models.User", "LinkedUser")
                        .WithMany()
                        .HasForeignKey("LinkedUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Bank");

                    b.Navigation("DevelopmentUser");

                    b.Navigation("LinkedUser");
                });

            modelBuilder.Entity("FraudGuard.Api.Models.FraudAlert", b =>
                {
                    b.HasOne("FraudGuard.Api.Models.Prediction", "Prediction")
                        .WithMany()
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FraudGuard.Api.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FraudGuard.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Prediction");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FraudGuard.Api.Models.FraudCase", b =>
                {
                    b.HasOne("FraudGuard.Api.Models.User", "AssignedAnalyst")
                        .WithMany()
                        .HasForeignKey("AssignedAnalystId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FraudGuard.Api.Models.FraudAlert", "FraudAlert")
                        .WithMany()
                        .HasForeignKey("FraudAlertId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FraudGuard.Api.Models.Prediction", "Prediction")
                        .WithMany()
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FraudGuard.Api.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssignedAnalyst");

                    b.Navigation("FraudAlert");

                    b.Navigation("Prediction");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FraudGuard.Api.Models.Merchant", b =>
                {
                    b.HasOne("FraudGuard.Api.Models.BankAccount", "SettlementBankAccount")
                        .WithMany()
                        .HasForeignKey("SettlementBankAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SettlementBankAccount");
                });

            modelBuilder.Entity("FraudGuard.Api.Models.Prediction", b =>
                {
                    b.HasOne("FraudGuard.Api.Models.Transaction", "Transaction")
                        .WithMany("Predictions")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FraudGuard.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FraudGuard.Api.Models.Transaction", b =>
                {
                    b.HasOne("FraudGuard.Api.Models.Beneficiary", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FraudGuard.Api.Models.Merchant", "MerchantRecord")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FraudGuard.Api.Models.BankAccount", "SourceBankAccount")
                        .WithMany()
                        .HasForeignKey("SourceBankAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FraudGuard.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("MerchantRecord");

                    b.Navigation("SourceBankAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FraudGuard.Api.Models.Bank", b =>
                {
                    b.Navigation("BankAccounts");
                });

            modelBuilder.Entity("FraudGuard.Api.Models.Transaction", b =>
                {
                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
