import { Topbar } from "@/components/layout/Topbar";
import { BrainCircuit, Database, GraduationCap, Layers, type LucideIcon } from "lucide-react";

export default function Thesis() {
  return (
    <>
      <Topbar title="Research" subtitle="FraudGuard-AI methodology, system scope, and results" />
      <main className="flex-1 p-4 md:p-8 space-y-6">
        <div className="glass rounded-3xl p-8 relative overflow-hidden">
          <div className="absolute inset-0 bg-mesh opacity-60" />
          <div className="relative max-w-3xl">
            <div className="inline-flex items-center gap-2 rounded-full glass px-3 py-1 text-xs">
              <GraduationCap className="h-3 w-3 text-primary" /> FraudGuard-AI Machine Learning Project
            </div>
            <h1 className="mt-4 text-3xl md:text-4xl font-display font-semibold">
              Online Payment Fraud Detection using <span className="text-gradient">Machine Learning</span>
            </h1>
            <p className="mt-4 text-muted-foreground">
              FraudGuard-AI studies supervised and unsupervised machine learning for detecting fraudulent online payment
              transactions. The implemented system combines a scikit-learn experiment workflow, a Python FastAPI
              prediction service, an ASP.NET Core Web API, and a React/Vite dashboard for prediction, history, alerts,
              reports, and administrative review.
            </p>
            <div className="mt-6 flex flex-wrap gap-3">
              <Meta icon={Database} label="Dataset" value="ml/dataset/fraud.csv" />
              <Meta icon={BrainCircuit} label="Models" value="LR, KNN, DT, RF, MLPClassifier" />
              <Meta icon={Layers} label="Clustering" value="KMeans with PCA" />
            </div>
          </div>
        </div>

        <div className="grid lg:grid-cols-3 gap-4">
          <Block
            title="Problem statement"
            body="Online payment fraud is a real-world classification problem where legitimate and fraudulent transactions must be separated from transaction type, amount, and balance movement features."
          />
          <Block
            title="Research questions"
            body="Which scikit-learn classifiers perform best on the fraud transaction dataset, how does feature selection affect performance, and what can KMeans clustering reveal about transaction group structure?"
          />
          <Block
            title="Contributions"
            body="The project compares Logistic Regression, KNN, Decision Tree, Random Forest, and MLPClassifier; exports metrics and artifacts; and integrates prediction workflows into the full-stack application."
          />
        </div>

        <div className="grid lg:grid-cols-2 gap-4">
          <Block
            title="Methodology"
            body="The notebook loads ml/dataset/fraud.csv, preprocesses transaction features, applies stratified train/test splitting, handles imbalance with class-weighted models where supported, runs SelectKBest, tunes models with GridSearchCV, and evaluates confusion matrices and classification metrics."
          />
          <Block
            title="Results"
            body="The exported model comparison results select Random Forest by held-out F1-score in the current notebook run. The admin model comparison page reads the generated JSON/CSV files for accuracy, precision, recall, F1-score, ROC-AUC, and confusion matrices."
          />
        </div>

        <div className="grid lg:grid-cols-3 gap-4">
          <Block
            title="Implemented system"
            body="Authenticated users can create transactions, request fraud predictions, review prediction history, and inspect alerts and reports generated by the application workflows."
          />
          <Block
            title="Admin review"
            body="Administrators can review users, transactions, prediction history, alerts, logs, dashboard metrics, and model comparison exports from the ASP.NET Core backend."
          />
          <Block
            title="Visual analysis"
            body="Reports and model comparison pages show charts and exported ML artifacts, including feature importance, confusion matrices, KMeans clustering results, and PCA visualizations when available."
          />
        </div>

        <div className="glass rounded-2xl p-6">
          <p className="font-display font-semibold">Tech stack</p>
          <div className="mt-3 grid md:grid-cols-3 gap-3 text-sm">
            <div>
              <p className="text-xs text-muted-foreground">Frontend</p>
              <p>React - Vite - TanStack Router - Tailwind - Recharts</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Backend</p>
              <p>ASP.NET Core Web API - JWT authentication - SQL Server</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Machine Learning</p>
              <p>Python - FastAPI - Pandas - NumPy - scikit-learn</p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

function Meta({ icon: Icon, label, value }: { icon: LucideIcon; label: string; value: string }) {
  return (
    <div className="glass rounded-lg px-3 py-2 flex items-center gap-2">
      <Icon className="h-4 w-4 text-primary" />
      <div>
        <p className="text-[10px] text-muted-foreground">{label}</p>
        <p className="text-xs font-medium">{value}</p>
      </div>
    </div>
  );
}

function Block({ title, body }: { title: string; body: string }) {
  return (
    <div className="glass rounded-2xl p-5">
      <p className="font-display font-semibold">{title}</p>
      <p className="text-sm text-muted-foreground mt-2">{body}</p>
    </div>
  );
}
