/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppIndexRouteImport } from './routes/_app.app.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as AppAppTransactionsRouteImport } from './routes/_app.app.transactions'
import { Route as AppAppThesisRouteImport } from './routes/_app.app.thesis'
import { Route as AppAppReportsRouteImport } from './routes/_app.app.reports'
import { Route as AppAppProfileRouteImport } from './routes/_app.app.profile'
import { Route as AppAppPredictRouteImport } from './routes/_app.app.predict'
import { Route as AppAppPipelineRouteImport } from './routes/_app.app.pipeline'
import { Route as AppAppModelsRouteImport } from './routes/_app.app.models'
import { Route as AppAppAlertsRouteImport } from './routes/_app.app.alerts'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminTransactionsRouteImport } from './routes/_admin.admin.transactions'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminModelsRouteImport } from './routes/_admin.admin.models'
import { Route as AdminAdminLogsRouteImport } from './routes/_admin.admin.logs'
import { Route as AdminAdminAlertsRouteImport } from './routes/_admin.admin.alerts'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AppAppTransactionsRoute = AppAppTransactionsRouteImport.update({
  id: '/app/transactions',
  path: '/app/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppAppThesisRoute = AppAppThesisRouteImport.update({
  id: '/app/thesis',
  path: '/app/thesis',
  getParentRoute: () => AppRoute,
} as any)
const AppAppReportsRoute = AppAppReportsRouteImport.update({
  id: '/app/reports',
  path: '/app/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAppProfileRoute = AppAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppAppPredictRoute = AppAppPredictRouteImport.update({
  id: '/app/predict',
  path: '/app/predict',
  getParentRoute: () => AppRoute,
} as any)
const AppAppPipelineRoute = AppAppPipelineRouteImport.update({
  id: '/app/pipeline',
  path: '/app/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppAppModelsRoute = AppAppModelsRouteImport.update({
  id: '/app/models',
  path: '/app/models',
  getParentRoute: () => AppRoute,
} as any)
const AppAppAlertsRoute = AppAppAlertsRouteImport.update({
  id: '/app/alerts',
  path: '/app/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminTransactionsRoute = AdminAdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminModelsRoute = AdminAdminModelsRouteImport.update({
  id: '/admin/models',
  path: '/admin/models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLogsRoute = AdminAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAlertsRoute = AdminAdminAlertsRouteImport.update({
  id: '/admin/alerts',
  path: '/admin/alerts',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/alerts': typeof AdminAdminAlertsRoute
  '/admin/logs': typeof AdminAdminLogsRoute
  '/admin/models': typeof AdminAdminModelsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/transactions': typeof AdminAdminTransactionsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/app/alerts': typeof AppAppAlertsRoute
  '/app/models': typeof AppAppModelsRoute
  '/app/pipeline': typeof AppAppPipelineRoute
  '/app/predict': typeof AppAppPredictRoute
  '/app/profile': typeof AppAppProfileRoute
  '/app/reports': typeof AppAppReportsRoute
  '/app/thesis': typeof AppAppThesisRoute
  '/app/transactions': typeof AppAppTransactionsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/app/': typeof AppAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/alerts': typeof AdminAdminAlertsRoute
  '/admin/logs': typeof AdminAdminLogsRoute
  '/admin/models': typeof AdminAdminModelsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/transactions': typeof AdminAdminTransactionsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/app/alerts': typeof AppAppAlertsRoute
  '/app/models': typeof AppAppModelsRoute
  '/app/pipeline': typeof AppAppPipelineRoute
  '/app/predict': typeof AppAppPredictRoute
  '/app/profile': typeof AppAppProfileRoute
  '/app/reports': typeof AppAppReportsRoute
  '/app/thesis': typeof AppAppThesisRoute
  '/app/transactions': typeof AppAppTransactionsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/app': typeof AppAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_admin/admin/alerts': typeof AdminAdminAlertsRoute
  '/_admin/admin/logs': typeof AdminAdminLogsRoute
  '/_admin/admin/models': typeof AdminAdminModelsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/transactions': typeof AdminAdminTransactionsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_app/app/alerts': typeof AppAppAlertsRoute
  '/_app/app/models': typeof AppAppModelsRoute
  '/_app/app/pipeline': typeof AppAppPipelineRoute
  '/_app/app/predict': typeof AppAppPredictRoute
  '/_app/app/profile': typeof AppAppProfileRoute
  '/_app/app/reports': typeof AppAppReportsRoute
  '/_app/app/thesis': typeof AppAppThesisRoute
  '/_app/app/transactions': typeof AppAppTransactionsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_app/app/': typeof AppAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/alerts'
    | '/admin/logs'
    | '/admin/models'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/app/alerts'
    | '/app/models'
    | '/app/pipeline'
    | '/app/predict'
    | '/app/profile'
    | '/app/reports'
    | '/app/thesis'
    | '/app/transactions'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/alerts'
    | '/admin/logs'
    | '/admin/models'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/app/alerts'
    | '/app/models'
    | '/app/pipeline'
    | '/app/predict'
    | '/app/profile'
    | '/app/reports'
    | '/app/thesis'
    | '/app/transactions'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_admin/admin/alerts'
    | '/_admin/admin/logs'
    | '/_admin/admin/models'
    | '/_admin/admin/settings'
    | '/_admin/admin/transactions'
    | '/_admin/admin/users'
    | '/_app/app/alerts'
    | '/_app/app/models'
    | '/_app/app/pipeline'
    | '/_app/app/predict'
    | '/_app/app/profile'
    | '/_app/app/reports'
    | '/_app/app/thesis'
    | '/_app/app/transactions'
    | '/_admin/admin/'
    | '/_app/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/app/transactions': {
      id: '/_app/app/transactions'
      path: '/app/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppAppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/thesis': {
      id: '/_app/app/thesis'
      path: '/app/thesis'
      fullPath: '/app/thesis'
      preLoaderRoute: typeof AppAppThesisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/reports': {
      id: '/_app/app/reports'
      path: '/app/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppAppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/profile': {
      id: '/_app/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppAppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/predict': {
      id: '/_app/app/predict'
      path: '/app/predict'
      fullPath: '/app/predict'
      preLoaderRoute: typeof AppAppPredictRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/pipeline': {
      id: '/_app/app/pipeline'
      path: '/app/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppAppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/models': {
      id: '/_app/app/models'
      path: '/app/models'
      fullPath: '/app/models'
      preLoaderRoute: typeof AppAppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/alerts': {
      id: '/_app/app/alerts'
      path: '/app/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/transactions': {
      id: '/_admin/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminAdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/models': {
      id: '/_admin/admin/models'
      path: '/admin/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminAdminModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/logs': {
      id: '/_admin/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminAdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/alerts': {
      id: '/_admin/admin/alerts'
      path: '/admin/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAlertsRoute: typeof AdminAdminAlertsRoute
  AdminAdminLogsRoute: typeof AdminAdminLogsRoute
  AdminAdminModelsRoute: typeof AdminAdminModelsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminTransactionsRoute: typeof AdminAdminTransactionsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAlertsRoute: AdminAdminAlertsRoute,
  AdminAdminLogsRoute: AdminAdminLogsRoute,
  AdminAdminModelsRoute: AdminAdminModelsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminTransactionsRoute: AdminAdminTransactionsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAppAlertsRoute: typeof AppAppAlertsRoute
  AppAppModelsRoute: typeof AppAppModelsRoute
  AppAppPipelineRoute: typeof AppAppPipelineRoute
  AppAppPredictRoute: typeof AppAppPredictRoute
  AppAppProfileRoute: typeof AppAppProfileRoute
  AppAppReportsRoute: typeof AppAppReportsRoute
  AppAppThesisRoute: typeof AppAppThesisRoute
  AppAppTransactionsRoute: typeof AppAppTransactionsRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppAlertsRoute: AppAppAlertsRoute,
  AppAppModelsRoute: AppAppModelsRoute,
  AppAppPipelineRoute: AppAppPipelineRoute,
  AppAppPredictRoute: AppAppPredictRoute,
  AppAppProfileRoute: AppAppProfileRoute,
  AppAppReportsRoute: AppAppReportsRoute,
  AppAppThesisRoute: AppAppThesisRoute,
  AppAppTransactionsRoute: AppAppTransactionsRoute,
  AppAppIndexRoute: AppAppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
