/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppTransactionsRouteImport } from './routes/app/transactions'
import { Route as AppThesisRouteImport } from './routes/app/thesis'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppPredictRouteImport } from './routes/app/predict'
import { Route as AppPipelineRouteImport } from './routes/app/pipeline'
import { Route as AppModelsRouteImport } from './routes/app/models'
import { Route as AppAlertsRouteImport } from './routes/app/alerts'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminModelsRouteImport } from './routes/admin/models'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminAlertsRouteImport } from './routes/admin/alerts'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/app/transactions',
  path: '/app/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppThesisRoute = AppThesisRouteImport.update({
  id: '/app/thesis',
  path: '/app/thesis',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/app/reports',
  path: '/app/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPredictRoute = AppPredictRouteImport.update({
  id: '/app/predict',
  path: '/app/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/app/pipeline',
  path: '/app/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/app/models',
  path: '/app/models',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/app/alerts',
  path: '/app/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/admin/models',
  path: '/admin/models',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/admin/alerts',
  path: '/admin/alerts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/models': typeof AppModelsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/predict': typeof AppPredictRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/thesis': typeof AppThesisRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/models': typeof AppModelsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/predict': typeof AppPredictRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/thesis': typeof AppThesisRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/models': typeof AppModelsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/predict': typeof AppPredictRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/thesis': typeof AppThesisRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/alerts'
    | '/admin/logs'
    | '/admin/models'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/app/alerts'
    | '/app/models'
    | '/app/pipeline'
    | '/app/predict'
    | '/app/profile'
    | '/app/reports'
    | '/app/thesis'
    | '/app/transactions'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/alerts'
    | '/admin/logs'
    | '/admin/models'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/app/alerts'
    | '/app/models'
    | '/app/pipeline'
    | '/app/predict'
    | '/app/profile'
    | '/app/reports'
    | '/app/thesis'
    | '/app/transactions'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/alerts'
    | '/admin/logs'
    | '/admin/models'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/app/alerts'
    | '/app/models'
    | '/app/pipeline'
    | '/app/predict'
    | '/app/profile'
    | '/app/reports'
    | '/app/thesis'
    | '/app/transactions'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppModelsRoute: typeof AppModelsRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppPredictRoute: typeof AppPredictRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppThesisRoute: typeof AppThesisRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/app/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/thesis': {
      id: '/app/thesis'
      path: '/app/thesis'
      fullPath: '/app/thesis'
      preLoaderRoute: typeof AppThesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/app/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/predict': {
      id: '/app/predict'
      path: '/app/predict'
      fullPath: '/app/predict'
      preLoaderRoute: typeof AppPredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/app/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/models': {
      id: '/app/models'
      path: '/app/models'
      fullPath: '/app/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/app/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/admin/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/admin/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppModelsRoute: AppModelsRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppPredictRoute: AppPredictRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppThesisRoute: AppThesisRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
