/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AnalystIndexRouteImport } from './routes/analyst/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppTransactionsRouteImport } from './routes/app/transactions'
import { Route as AppThesisRouteImport } from './routes/app/thesis'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppPredictFraudRouteImport } from './routes/app/predict-fraud'
import { Route as AppPredictRouteImport } from './routes/app/predict'
import { Route as AppPipelineRouteImport } from './routes/app/pipeline'
import { Route as AppModelsRouteImport } from './routes/app/models'
import { Route as AppBeneficiariesRouteImport } from './routes/app/beneficiaries'
import { Route as AppAlertsRouteImport } from './routes/app/alerts'
import { Route as AppAccountsRouteImport } from './routes/app/accounts'
import { Route as AnalystTransactionsRouteImport } from './routes/analyst/transactions'
import { Route as AnalystReviewQueueRouteImport } from './routes/analyst/review-queue'
import { Route as AnalystReportsRouteImport } from './routes/analyst/reports'
import { Route as AnalystProfileRouteImport } from './routes/analyst/profile'
import { Route as AnalystPredictionsRouteImport } from './routes/analyst/predictions'
import { Route as AnalystInvestigationsRouteImport } from './routes/analyst/investigations'
import { Route as AnalystFraudAlertsRouteImport } from './routes/analyst/fraud-alerts'
import { Route as AnalystAlertsRouteImport } from './routes/analyst/alerts'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminPredictionsRouteImport } from './routes/admin/predictions'
import { Route as AdminModelComparisonRouteImport } from './routes/admin/model-comparison'
import { Route as AdminMerchantsRouteImport } from './routes/admin/merchants'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminAlertsRouteImport } from './routes/admin/alerts'
import { Route as AnalystInvestigationsIndexRouteImport } from './routes/analyst/investigations.index'
import { Route as AnalystInvestigationsCaseIdRouteImport } from './routes/analyst/investigations.$caseId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystIndexRoute = AnalystIndexRouteImport.update({
  id: '/analyst/',
  path: '/analyst/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/app/transactions',
  path: '/app/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppThesisRoute = AppThesisRouteImport.update({
  id: '/app/thesis',
  path: '/app/thesis',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/app/reports',
  path: '/app/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPredictFraudRoute = AppPredictFraudRouteImport.update({
  id: '/app/predict-fraud',
  path: '/app/predict-fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPredictRoute = AppPredictRouteImport.update({
  id: '/app/predict',
  path: '/app/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/app/pipeline',
  path: '/app/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/app/models',
  path: '/app/models',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBeneficiariesRoute = AppBeneficiariesRouteImport.update({
  id: '/app/beneficiaries',
  path: '/app/beneficiaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/app/alerts',
  path: '/app/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/app/accounts',
  path: '/app/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystTransactionsRoute = AnalystTransactionsRouteImport.update({
  id: '/analyst/transactions',
  path: '/analyst/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystReviewQueueRoute = AnalystReviewQueueRouteImport.update({
  id: '/analyst/review-queue',
  path: '/analyst/review-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystReportsRoute = AnalystReportsRouteImport.update({
  id: '/analyst/reports',
  path: '/analyst/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystProfileRoute = AnalystProfileRouteImport.update({
  id: '/analyst/profile',
  path: '/analyst/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystPredictionsRoute = AnalystPredictionsRouteImport.update({
  id: '/analyst/predictions',
  path: '/analyst/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystInvestigationsRoute = AnalystInvestigationsRouteImport.update({
  id: '/analyst/investigations',
  path: '/analyst/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystFraudAlertsRoute = AnalystFraudAlertsRouteImport.update({
  id: '/analyst/fraud-alerts',
  path: '/analyst/fraud-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystAlertsRoute = AnalystAlertsRouteImport.update({
  id: '/analyst/alerts',
  path: '/analyst/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPredictionsRoute = AdminPredictionsRouteImport.update({
  id: '/admin/predictions',
  path: '/admin/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModelComparisonRoute = AdminModelComparisonRouteImport.update({
  id: '/admin/model-comparison',
  path: '/admin/model-comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/admin/merchants',
  path: '/admin/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/admin/alerts',
  path: '/admin/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystInvestigationsIndexRoute =
  AnalystInvestigationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AnalystInvestigationsRoute,
  } as any)
const AnalystInvestigationsCaseIdRoute =
  AnalystInvestigationsCaseIdRouteImport.update({
    id: '/$caseId',
    path: '/$caseId',
    getParentRoute: () => AnalystInvestigationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/model-comparison': typeof AdminModelComparisonRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/analyst/alerts': typeof AnalystAlertsRoute
  '/analyst/fraud-alerts': typeof AnalystFraudAlertsRoute
  '/analyst/investigations': typeof AnalystInvestigationsRouteWithChildren
  '/analyst/predictions': typeof AnalystPredictionsRoute
  '/analyst/profile': typeof AnalystProfileRoute
  '/analyst/reports': typeof AnalystReportsRoute
  '/analyst/review-queue': typeof AnalystReviewQueueRoute
  '/analyst/transactions': typeof AnalystTransactionsRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/beneficiaries': typeof AppBeneficiariesRoute
  '/app/models': typeof AppModelsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/predict': typeof AppPredictRoute
  '/app/predict-fraud': typeof AppPredictFraudRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/thesis': typeof AppThesisRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/analyst/': typeof AnalystIndexRoute
  '/app/': typeof AppIndexRoute
  '/analyst/investigations/$caseId': typeof AnalystInvestigationsCaseIdRoute
  '/analyst/investigations/': typeof AnalystInvestigationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/model-comparison': typeof AdminModelComparisonRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/analyst/alerts': typeof AnalystAlertsRoute
  '/analyst/fraud-alerts': typeof AnalystFraudAlertsRoute
  '/analyst/predictions': typeof AnalystPredictionsRoute
  '/analyst/profile': typeof AnalystProfileRoute
  '/analyst/reports': typeof AnalystReportsRoute
  '/analyst/review-queue': typeof AnalystReviewQueueRoute
  '/analyst/transactions': typeof AnalystTransactionsRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/beneficiaries': typeof AppBeneficiariesRoute
  '/app/models': typeof AppModelsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/predict': typeof AppPredictRoute
  '/app/predict-fraud': typeof AppPredictFraudRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/thesis': typeof AppThesisRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/admin': typeof AdminIndexRoute
  '/analyst': typeof AnalystIndexRoute
  '/app': typeof AppIndexRoute
  '/analyst/investigations/$caseId': typeof AnalystInvestigationsCaseIdRoute
  '/analyst/investigations': typeof AnalystInvestigationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/model-comparison': typeof AdminModelComparisonRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/analyst/alerts': typeof AnalystAlertsRoute
  '/analyst/fraud-alerts': typeof AnalystFraudAlertsRoute
  '/analyst/investigations': typeof AnalystInvestigationsRouteWithChildren
  '/analyst/predictions': typeof AnalystPredictionsRoute
  '/analyst/profile': typeof AnalystProfileRoute
  '/analyst/reports': typeof AnalystReportsRoute
  '/analyst/review-queue': typeof AnalystReviewQueueRoute
  '/analyst/transactions': typeof AnalystTransactionsRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/beneficiaries': typeof AppBeneficiariesRoute
  '/app/models': typeof AppModelsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/predict': typeof AppPredictRoute
  '/app/predict-fraud': typeof AppPredictFraudRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/thesis': typeof AppThesisRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/analyst/': typeof AnalystIndexRoute
  '/app/': typeof AppIndexRoute
  '/analyst/investigations/$caseId': typeof AnalystInvestigationsCaseIdRoute
  '/analyst/investigations/': typeof AnalystInvestigationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/admin/alerts'
    | '/admin/logs'
    | '/admin/merchants'
    | '/admin/model-comparison'
    | '/admin/predictions'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/analyst/alerts'
    | '/analyst/fraud-alerts'
    | '/analyst/investigations'
    | '/analyst/predictions'
    | '/analyst/profile'
    | '/analyst/reports'
    | '/analyst/review-queue'
    | '/analyst/transactions'
    | '/app/accounts'
    | '/app/alerts'
    | '/app/beneficiaries'
    | '/app/models'
    | '/app/pipeline'
    | '/app/predict'
    | '/app/predict-fraud'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/thesis'
    | '/app/transactions'
    | '/admin/'
    | '/analyst/'
    | '/app/'
    | '/analyst/investigations/$caseId'
    | '/analyst/investigations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/admin/alerts'
    | '/admin/logs'
    | '/admin/merchants'
    | '/admin/model-comparison'
    | '/admin/predictions'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/analyst/alerts'
    | '/analyst/fraud-alerts'
    | '/analyst/predictions'
    | '/analyst/profile'
    | '/analyst/reports'
    | '/analyst/review-queue'
    | '/analyst/transactions'
    | '/app/accounts'
    | '/app/alerts'
    | '/app/beneficiaries'
    | '/app/models'
    | '/app/pipeline'
    | '/app/predict'
    | '/app/predict-fraud'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/thesis'
    | '/app/transactions'
    | '/admin'
    | '/analyst'
    | '/app'
    | '/analyst/investigations/$caseId'
    | '/analyst/investigations'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/admin/alerts'
    | '/admin/logs'
    | '/admin/merchants'
    | '/admin/model-comparison'
    | '/admin/predictions'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/analyst/alerts'
    | '/analyst/fraud-alerts'
    | '/analyst/investigations'
    | '/analyst/predictions'
    | '/analyst/profile'
    | '/analyst/reports'
    | '/analyst/review-queue'
    | '/analyst/transactions'
    | '/app/accounts'
    | '/app/alerts'
    | '/app/beneficiaries'
    | '/app/models'
    | '/app/pipeline'
    | '/app/predict'
    | '/app/predict-fraud'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/thesis'
    | '/app/transactions'
    | '/admin/'
    | '/analyst/'
    | '/app/'
    | '/analyst/investigations/$caseId'
    | '/analyst/investigations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminModelComparisonRoute: typeof AdminModelComparisonRoute
  AdminPredictionsRoute: typeof AdminPredictionsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AnalystAlertsRoute: typeof AnalystAlertsRoute
  AnalystFraudAlertsRoute: typeof AnalystFraudAlertsRoute
  AnalystInvestigationsRoute: typeof AnalystInvestigationsRouteWithChildren
  AnalystPredictionsRoute: typeof AnalystPredictionsRoute
  AnalystProfileRoute: typeof AnalystProfileRoute
  AnalystReportsRoute: typeof AnalystReportsRoute
  AnalystReviewQueueRoute: typeof AnalystReviewQueueRoute
  AnalystTransactionsRoute: typeof AnalystTransactionsRoute
  AppAccountsRoute: typeof AppAccountsRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppBeneficiariesRoute: typeof AppBeneficiariesRoute
  AppModelsRoute: typeof AppModelsRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppPredictRoute: typeof AppPredictRoute
  AppPredictFraudRoute: typeof AppPredictFraudRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppThesisRoute: typeof AppThesisRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AnalystIndexRoute: typeof AnalystIndexRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst/': {
      id: '/analyst/'
      path: '/analyst'
      fullPath: '/analyst/'
      preLoaderRoute: typeof AnalystIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/app/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/thesis': {
      id: '/app/thesis'
      path: '/app/thesis'
      fullPath: '/app/thesis'
      preLoaderRoute: typeof AppThesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/app/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/predict-fraud': {
      id: '/app/predict-fraud'
      path: '/app/predict-fraud'
      fullPath: '/app/predict-fraud'
      preLoaderRoute: typeof AppPredictFraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/predict': {
      id: '/app/predict'
      path: '/app/predict'
      fullPath: '/app/predict'
      preLoaderRoute: typeof AppPredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/app/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/models': {
      id: '/app/models'
      path: '/app/models'
      fullPath: '/app/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/beneficiaries': {
      id: '/app/beneficiaries'
      path: '/app/beneficiaries'
      fullPath: '/app/beneficiaries'
      preLoaderRoute: typeof AppBeneficiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/app/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/app/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst/transactions': {
      id: '/analyst/transactions'
      path: '/analyst/transactions'
      fullPath: '/analyst/transactions'
      preLoaderRoute: typeof AnalystTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst/review-queue': {
      id: '/analyst/review-queue'
      path: '/analyst/review-queue'
      fullPath: '/analyst/review-queue'
      preLoaderRoute: typeof AnalystReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst/reports': {
      id: '/analyst/reports'
      path: '/analyst/reports'
      fullPath: '/analyst/reports'
      preLoaderRoute: typeof AnalystReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst/profile': {
      id: '/analyst/profile'
      path: '/analyst/profile'
      fullPath: '/analyst/profile'
      preLoaderRoute: typeof AnalystProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst/predictions': {
      id: '/analyst/predictions'
      path: '/analyst/predictions'
      fullPath: '/analyst/predictions'
      preLoaderRoute: typeof AnalystPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst/investigations': {
      id: '/analyst/investigations'
      path: '/analyst/investigations'
      fullPath: '/analyst/investigations'
      preLoaderRoute: typeof AnalystInvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst/fraud-alerts': {
      id: '/analyst/fraud-alerts'
      path: '/analyst/fraud-alerts'
      fullPath: '/analyst/fraud-alerts'
      preLoaderRoute: typeof AnalystFraudAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst/alerts': {
      id: '/analyst/alerts'
      path: '/analyst/alerts'
      fullPath: '/analyst/alerts'
      preLoaderRoute: typeof AnalystAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/predictions': {
      id: '/admin/predictions'
      path: '/admin/predictions'
      fullPath: '/admin/predictions'
      preLoaderRoute: typeof AdminPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/model-comparison': {
      id: '/admin/model-comparison'
      path: '/admin/model-comparison'
      fullPath: '/admin/model-comparison'
      preLoaderRoute: typeof AdminModelComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/admin/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/admin/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst/investigations/': {
      id: '/analyst/investigations/'
      path: '/'
      fullPath: '/analyst/investigations/'
      preLoaderRoute: typeof AnalystInvestigationsIndexRouteImport
      parentRoute: typeof AnalystInvestigationsRoute
    }
    '/analyst/investigations/$caseId': {
      id: '/analyst/investigations/$caseId'
      path: '/$caseId'
      fullPath: '/analyst/investigations/$caseId'
      preLoaderRoute: typeof AnalystInvestigationsCaseIdRouteImport
      parentRoute: typeof AnalystInvestigationsRoute
    }
  }
}

interface AnalystInvestigationsRouteChildren {
  AnalystInvestigationsCaseIdRoute: typeof AnalystInvestigationsCaseIdRoute
  AnalystInvestigationsIndexRoute: typeof AnalystInvestigationsIndexRoute
}

const AnalystInvestigationsRouteChildren: AnalystInvestigationsRouteChildren = {
  AnalystInvestigationsCaseIdRoute: AnalystInvestigationsCaseIdRoute,
  AnalystInvestigationsIndexRoute: AnalystInvestigationsIndexRoute,
}

const AnalystInvestigationsRouteWithChildren =
  AnalystInvestigationsRoute._addFileChildren(
    AnalystInvestigationsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminModelComparisonRoute: AdminModelComparisonRoute,
  AdminPredictionsRoute: AdminPredictionsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AnalystAlertsRoute: AnalystAlertsRoute,
  AnalystFraudAlertsRoute: AnalystFraudAlertsRoute,
  AnalystInvestigationsRoute: AnalystInvestigationsRouteWithChildren,
  AnalystPredictionsRoute: AnalystPredictionsRoute,
  AnalystProfileRoute: AnalystProfileRoute,
  AnalystReportsRoute: AnalystReportsRoute,
  AnalystReviewQueueRoute: AnalystReviewQueueRoute,
  AnalystTransactionsRoute: AnalystTransactionsRoute,
  AppAccountsRoute: AppAccountsRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppBeneficiariesRoute: AppBeneficiariesRoute,
  AppModelsRoute: AppModelsRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppPredictRoute: AppPredictRoute,
  AppPredictFraudRoute: AppPredictFraudRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppThesisRoute: AppThesisRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AnalystIndexRoute: AnalystIndexRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
